import {useEffect,useState} from "react";
import {api} from "../api/client";

const labels={milestone:"Pencapaian",growth_check:"Cek pertumbuhan",routine:"Rutinitas",custom:"Lainnya"};
const states={upcoming:["Akan datang","bg-sky-soft text-sky"],due:["Minggu ini","bg-feed-soft text-feed"],overdue:["Lewat target","bg-warn/10 text-warn"],completed:["Selesai","bg-diaper-soft text-diaper"]};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});

export default function DevelopmentGoals({child,onClose}){
 const [data,setData]=useState({items:[],can_create:false});const [status,setStatus]=useState("loading");const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState(null);const [error,setError]=useState("");
 const [category,setCategory]=useState("milestone"),[title,setTitle]=useState(""),[targetDate,setTargetDate]=useState(today()),[note,setNote]=useState("");
 const load=async()=>{setStatus("loading");try{setData(await api.listDevelopmentGoals(child.id));setStatus("ready");}catch(e){setError(e.message);setStatus("error");}};useEffect(()=>{load();},[child.id]); // eslint-disable-line react-hooks/exhaustive-deps
 const open=(goal=null)=>{setEditing(goal);setCategory(goal?.category||"milestone");setTitle(goal?.title||"");setTargetDate(goal?.target_date||today());setNote(goal?.note||"");setShowForm(true);};
 const save=async(e)=>{e.preventDefault();setError("");try{const payload={category,title,target_date:targetDate,note:note||null};if(editing)await api.updateDevelopmentGoal(editing.id,payload);else await api.createDevelopmentGoal(child.id,payload);setShowForm(false);await load();}catch(err){setError(err.message);}};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-void"><div className="mx-auto min-h-screen max-w-lg px-4 pb-20 pt-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-sleep">Rencana keluarga</p><h1 className="font-display text-3xl font-bold text-ink">Tujuan Perkembangan</h1></div><button onClick={onClose} className="rounded-full border border-void-hairline bg-white px-4 py-2 text-sm">Tutup</button></div>
 {status==="loading"?<p className="py-10 text-center text-sm text-ink-faint">Memuat tujuan...</p>:status==="error"?<p className="rounded-xl bg-warn/10 p-4 text-sm text-warn">{error}</p>:<><div className="mb-4 flex items-center justify-between"><p className="max-w-[70%] text-xs text-ink-faint">{data.disclaimer}</p>{data.can_create&&<button onClick={()=>open()} className="rounded-full bg-feed px-4 py-2.5 text-xs font-bold text-white">+ Tujuan</button>}</div>{data.items.length===0?<div className="rounded-2xl border border-dashed border-void-hairline p-9 text-center"><div className="text-4xl">🎯</div><p className="mt-2 text-sm font-bold text-ink">Belum ada tujuan keluarga</p></div>:<div className="space-y-3">{data.items.map(goal=>{const state=states[goal.state];return <article key={goal.id} className="rounded-2xl border border-void-hairline bg-white p-4"><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${state[1]}`}>{state[0]}</span><h2 className="mt-2 text-sm font-bold text-ink">{goal.title}</h2><p className="mt-1 text-xs text-ink-muted">{labels[goal.category]} · target {goal.target_date}</p>{goal.note&&<p className="mt-2 text-xs text-ink-faint">{goal.note}</p>}</div><span className="text-xl">{goal.state==="completed"?"✅":"🎯"}</span></div><div className="mt-3 flex gap-3">{goal.can_complete&&<button onClick={async()=>{await api.completeDevelopmentGoal(goal.id);await load();}} className="text-xs font-bold text-diaper">Tandai selesai</button>}{goal.can_reopen&&<button onClick={async()=>{await api.reopenDevelopmentGoal(goal.id);await load();}} className="text-xs font-bold text-sleep">Buka lagi</button>}{goal.can_edit&&<><button onClick={()=>open(goal)} className="text-xs text-ink-muted">Edit</button><button onClick={async()=>{if(confirm("Hapus tujuan ini?")){await api.deleteDevelopmentGoal(goal.id);await load();}}} className="text-xs text-warn">Hapus</button></>}</div></article>})}</div>}</>}
 {showForm&&<div className="fixed inset-0 z-[60] flex items-end sm:items-center sm:justify-center"><div onClick={()=>setShowForm(false)} className="absolute inset-0 bg-black/50"/><form onSubmit={save} className="relative w-full rounded-t-2xl bg-white p-6 sm:max-w-sm sm:rounded-2xl"><h2 className="font-display text-2xl font-bold text-ink">{editing?"Edit tujuan":"Tujuan baru"}</h2><p className="mb-4 text-xs text-ink-faint">Gunakan rencana aktivitas/check-in, bukan target medis.</p><label className="mb-1 block text-xs text-ink-muted">Kategori</label><select value={category} onChange={e=>setCategory(e.target.value)} className="mb-3 w-full rounded-lg border border-void-hairline px-3 py-2.5">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label className="mb-1 block text-xs text-ink-muted">Judul</label><input maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} required className="mb-3 w-full rounded-lg border border-void-hairline px-3 py-2.5" placeholder="Contoh: Jadwalkan ukur tinggi"/><label className="mb-1 block text-xs text-ink-muted">Tanggal target</label><input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)} required className="mb-3 w-full rounded-lg border border-void-hairline px-3 py-2.5"/><label className="mb-1 block text-xs text-ink-muted">Catatan (opsional)</label><textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)} className="mb-3 w-full rounded-lg border border-void-hairline px-3 py-2.5"/>{error&&<p className="mb-3 text-sm text-warn">{error}</p>}<div className="flex gap-3"><button type="button" onClick={()=>setShowForm(false)} className="flex-1 rounded-lg border py-3">Batal</button><button className="flex-1 rounded-lg bg-feed py-3 font-bold text-white">Simpan</button></div></form></div>}
 </div></div>;
}
