import {useEffect,useState} from "react";
import {api} from "../api/client";

const AREAS={motor:"Gerak & motorik",communication:"Komunikasi",social:"Interaksi sosial",sleep:"Tidur",nutrition:"Makan & minum"};
const STATES={noticed:"Terlihat bulan ini",exploring:"Sedang dieksplorasi",not_checked:"Belum diamati"};
const monthWib=()=>{const p=new Intl.DateTimeFormat("en",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).formatToParts(new Date());return`${p.find(x=>x.type==="year").value}-${p.find(x=>x.type==="month").value}`;};
const initialAreas=()=>Object.fromEntries(Object.keys(AREAS).map(key=>[key,"not_checked"]));

export default function FamilyDevelopmentCheckIn({child,onClose}){
 const [data,setData]=useState({items:[],goals:[],can_create:false});const [status,setStatus]=useState("loading");const [error,setError]=useState("");const [form,setForm]=useState(false);const [editing,setEditing]=useState(null);
 const [period,setPeriod]=useState(monthWib),[areas,setAreas]=useState(initialAreas),[note,setNote]=useState(""),[discuss,setDiscuss]=useState(false),[goalId,setGoalId]=useState("");
 const load=async()=>{setStatus("loading");setError("");try{setData(await api.listFamilyCheckIns(child.id));setStatus("ready");}catch(e){setError(e.message);setStatus("error");}};useEffect(()=>{load();},[child.id]); // eslint-disable-line react-hooks/exhaustive-deps
 const open=(row=null)=>{setEditing(row);setPeriod(row?.period_month||monthWib());setAreas(row?.areas||initialAreas());setNote(row?.reflection_note||"");setDiscuss(Boolean(row?.discuss_with_professional));setGoalId(row?.linked_goal_id?String(row.linked_goal_id):"");setForm(true);setError("");};
 const save=async(e)=>{e.preventDefault();const payload={period_month:period,areas,reflection_note:note||null,discuss_with_professional:discuss,linked_goal_id:goalId?Number(goalId):null};try{if(editing)await api.updateFamilyCheckIn(editing.id,payload);else await api.createFamilyCheckIn(child.id,payload);setForm(false);await load();}catch(err){setError(err.message);}};
 return <div className="fixed inset-0 z-[80] overflow-y-auto bg-void"><div className="mx-auto min-h-screen max-w-lg px-4 pb-20 pt-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-sleep">Refleksi keluarga</p><h1 className="font-display text-2xl font-bold text-ink">Check-in Perkembangan</h1></div><button onClick={onClose} className="rounded-full border border-void-hairline bg-white px-4 py-2 text-sm">Tutup</button></div>
 <div className="my-4 rounded-2xl bg-sky-soft p-4 text-xs leading-relaxed text-sky">ℹ️ {data.disclaimer||"Ini adalah refleksi keluarga, bukan skrining atau diagnosis medis."}</div>
 {status==="loading"?<p className="py-12 text-center text-sm text-ink-faint">Memuat check-in...</p>:status==="error"?<p className="rounded-xl bg-warn/10 p-4 text-sm text-warn">{error}</p>:<><div className="mb-4 flex justify-end">{data.can_create&&<button onClick={()=>open()} className="rounded-full bg-feed px-4 py-2.5 text-xs font-bold text-white">+ Check-in</button>}</div>{data.items.length===0?<div className="rounded-2xl border border-dashed border-void-hairline p-9 text-center"><div className="text-4xl">🌱</div><p className="mt-2 text-sm font-bold text-ink">Belum ada refleksi bulanan</p></div>:<div className="space-y-3">{data.items.map(row=><article key={row.id} className="rounded-2xl border border-void-hairline bg-white p-4"><div className="flex justify-between"><div><p className="text-xs font-bold text-sleep">{new Date(`${row.period_month}-01T00:00:00`).toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</p><p className="mt-1 text-[11px] text-ink-faint">Oleh {row.created_by_name}</p></div>{row.discuss_with_professional&&<span className="rounded-full bg-feed-soft px-2 py-1 text-[10px] font-bold text-feed">Bahas saat konsultasi</span>}</div><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(row.areas).map(([key,value])=><div key={key} className="rounded-lg bg-void px-2 py-2"><p className="text-[10px] text-ink-faint">{AREAS[key]}</p><p className="text-xs font-semibold text-ink">{STATES[value]}</p></div>)}</div>{row.reflection_note&&<p className="mt-3 text-xs leading-relaxed text-ink-muted">{row.reflection_note}</p>}{row.linked_goal_title&&<p className="mt-2 text-xs text-sleep">🎯 {row.linked_goal_title}</p>}<div className="mt-3 flex gap-3">{row.can_edit&&<button onClick={()=>open(row)} className="text-xs font-bold text-sleep">Edit</button>}{row.can_delete&&<button onClick={async()=>{if(confirm("Hapus check-in ini?")){await api.deleteFamilyCheckIn(row.id);await load();}}} className="text-xs text-warn">Hapus</button>}</div></article>)}</div>}</>}
 {form&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/50 sm:items-center"><form onSubmit={save} className="max-h-[92vh] w-full max-w-md overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl"><div className="flex justify-between"><h2 className="text-lg font-bold text-ink">{editing?"Edit check-in":"Check-in bulanan"}</h2><button type="button" onClick={()=>setForm(false)} aria-label="Tutup form">✕</button></div><p className="mt-1 text-xs text-ink-faint">Tidak ada jawaban benar atau salah. Catat yang keluarga amati.</p><label className="mt-4 block text-xs font-semibold text-ink-muted">Bulan</label><input type="month" required value={period} onChange={e=>setPeriod(e.target.value)} className="mt-1 w-full rounded-lg border border-void-hairline p-2.5"/>
 {Object.entries(AREAS).map(([key,label])=><label key={key} className="mt-3 block text-xs font-semibold text-ink-muted">{label}<select value={areas[key]} onChange={e=>setAreas(old=>({...old,[key]:e.target.value}))} className="mt-1 w-full rounded-lg border border-void-hairline p-2.5">{Object.entries(STATES).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}
 <label className="mt-3 block text-xs font-semibold text-ink-muted">Catatan privat (opsional)</label><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} className="mt-1 w-full rounded-lg border border-void-hairline p-2.5" placeholder="Hal yang ingin diingat keluarga"/><label className="mt-3 flex gap-2 text-xs text-ink"><input type="checkbox" checked={discuss} onChange={e=>setDiscuss(e.target.checked)}/>Ingin dibahas dengan tenaga profesional</label><label className="mt-3 block text-xs font-semibold text-ink-muted">Hubungkan tujuan (opsional)</label><select value={goalId} onChange={e=>setGoalId(e.target.value)} className="mt-1 w-full rounded-lg border border-void-hairline p-2.5"><option value="">Tidak ditautkan</option>{data.goals.map(goal=><option key={goal.id} value={goal.id}>{goal.title}</option>)}</select>{error&&<p className="mt-3 text-sm text-warn">{error}</p>}<div className="mt-5 flex gap-3"><button type="button" onClick={()=>setForm(false)} className="flex-1 rounded-xl border py-3">Batal</button><button className="flex-1 rounded-xl bg-feed py-3 font-bold text-white">Simpan</button></div></form></div>}
 </div></div>;
}
